import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React from 'react';
import { useInView } from 'react-intersection-observer';


export default function Home() {
  const [home, homeInView] = useInView({
    threshold: 0.6,
  })
  const [staff, staffInView] = useInView({
    threshold: 0.5,
  })
  const [discord, discordInView] = useInView({
    threshold: 0.5,
  })
  const [league, leagueInView] = useInView({
    threshold: 0.5,
  })
  const [faq, faqInView] = useInView({
    threshold: 0.5,
  })
  const navBarStyle = !homeInView ? "navbar fixed-top navbar-expand-sm navbar-light bg-light" : "navbar fixed-top navbar-expand-sm navbar-dark";

  return (
    <div className={styles.container} id="container">
      <Head>
        <title>Team BaitMain - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <header className={styles.header}>
        <nav className={navBarStyle} id="navbar">
          <div className="container">
            <a className="navbar-brand" href="#home">Team Baitmain</a>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNav">
              <ul className="navbar-nav ms-auto" id="ul">
                <li className="nav-item">
                  <a className="nav-link" aria-current="page" href="#staff" style={staffInView ? {'color':'black'} : {}}>Staff</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#discord" style={discordInView ? {'color':'black'} : {}}>Discord</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#league" style={leagueInView ? {'color':'black'} : {}}>League of Legends</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#faq" style={faqInView ? {'color':'black'} : {}}>FAQ</a>
                </li>
                <li className="nav-item">
                  <Link href="/legal-notice"><a className="nav-link">Legal Notice</a></Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <main className={styles.main}>

        <section id="home" ref={home} className={styles.pagetitle}>
        <div className="container">
          <div className="row">
            <h1>
              <div className={styles.upper}>BAIT/</div>
              <br></br>
              <div className={styles.lower}>/MAIN</div>
            </h1>
          </div>
        </div>   
        </section>

        <section id="staff" ref={staff} className={styles.section}>
        <h2 className={styles.title && "text-center text-white"}>Our Staff</h2>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/images/roukee.png" width="150px" height="150px" alt=""/>
            <h2>roukee</h2>
            <p>Owner</p>
            <p>Admin</p>
            <p>Team-Manager</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/xb0sse.png" width="150px" height="150px" alt=""/>
            <h2>xB0sse</h2>
            <p>Co-Owner</p>
            <p>Lead Designer</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>zNewEra</h2>
            <p>Coder</p>
            <p>Designer</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/furz.jpg" width="150px" height="150px" alt=""/>
            <h2>Furzgraanaatr</h2>
            <p>Co-Owner</p>
            <p>Server Admin</p>
          </div>
        </div>
      </section>

      <section id="discord" ref={discord} className={styles.section}>
      <h2 className={styles.title && "text-center text-white"}>Join our Discord!</h2>
      <div className="text-center">
      <iframe src="https://discordapp.com/widget?id=247374778179125251&theme=dark" width="300" height="500" allowtransparency="true" frameBorder="0"></iframe>
		 	<h3><a href="https://discord.gg/Gj4q6Sr" className="text-white">Join</a></h3>
       </div>
      </section>

      <section id="league" ref={league} className={styles.section}>
        <h2 className={styles.title && "text-center text-white"}>Our Main Team</h2>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>Bopak</h2>
            <p>Top</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>zNewEra</h2>
            <p>Jungle</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>Atorim</h2>
            <p>Mid</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>SecondTimePC</h2>
            <p>Bottom</p>
          </div>
          <div className={styles.card}>
            <Image src="/images/missing.png" width="150px" height="150px" alt=""/>
            <h2>Deniz305</h2>
            <p>Support</p>
          </div>
        </div>
      </section>

      <section id="faq" ref={faq} className={styles.section}>
      <h2 className={styles.title && "text-center text-white"}>FAQ</h2>
      <div className="text-center">
        <div className={styles.question}>
        <p>Q: What games do you play?</p>
        <p>A: We play League of Legends, Fortnite and Call of Duty</p>
        </div>
        <div className={styles.question}>
        <p>Q: Where does your name come from?</p>
        <p>A: If only we knew that. They say it has something to do with players baiting each other...</p>
        </div>
        </div>
      </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}